# Generated by Django 2.0.2 on 2019-11-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bocy',
            new_name='body',
        ),
    ]
